SELECT * FROM Cricket

SELECT DISTINCT RUN FROM Cricket;

SELECT RUN FROM Cricket;

SELECT * FROM Cricket
WHERE PLAYERNAME ='Virat Kohli';

SELECT * FROM Cricket
WHERE PCODE = 1;

SELECT * FROM Cricket
WHERE RUN >5000;

SELECT * FROM Cricket
ORDER BY RUN;

SELECT * FROM Cricket
ORDER BY RUN DESC;

SELECT * FROM Cricket
WHERE COUNTRY ='India' AND WICKET=10;

SELECT * FROM Cricket
WHERE COUNTRY ='India' OR COUNTRY='Australia';

SELECT * FROM Cricket
WHERE NOT COUNTRY ='India';

UPDATE Cricket
SET WICKET =20
WHERE PCODE=1;

DELETE FROM Cricket WHERE PCODE =10;

SELECT TOP 3 * FROM Cricket;

SELECT TOP 3 * FROM Cricket
WHERE COUNTRY ='India';

SELECT MAX(RUN) AS Highest
FROM Cricket;

SELECT MIN(RUN) AS Smallest
FROM Cricket;

SELECT COUNT(*)
FROM Cricket;

SELECT SUM(RUN)
FROM Cricket;

SELECT SUM(WICKET)
FROM Cricket;

SELECT SUM(RUN)
FROM Cricket
WHERE PCODE =1;

SELECT AVG(RUN)  AS RUN
FROM Cricket;

SELECT * FROM Cricket
WHERE RUN > (SELECT AVG (RUN) FROM Cricket);

SELECT * FROM Cricket
WHERE RUN < (SELECT AVG (RUN) FROM Cricket);

SELECT * FROM Cricket
WHERE PLAYERNAME LIKE 'V%';

SELECT * FROM Cricket
WHERE PLAYERNAME LIKE '%V%';

SELECT * FROM Cricket
WHERE COUNTRY IN ('India','Australia');


SELECT * FROM Cricket
WHERE WICKET BETWEEN 5 AND 20;

SELECT * FROM Cricket
WHERE WICKET NOT BETWEEN 5 AND 20;


